language: node_js
node_js:
  - "8"
script:
  - yarn build
deploy:
  skip_cleanup: true
  provider: script
  script: yarn deploy
  on:
    all_branches: true
cache:
  yarn: true
  directories:
    - node_modules
